---
- name: "create station Station:{{ item.name }}"
  platform42.neo4j.vertex:
    instance_id: "{{ AURA_INSTANCEID }}"
    database: "{{ NEO4J_DATABASE }}"
    username: "{{ NEO4J_USERNAME }}"
    password: "{{ NEO4J_PASSWORD }}"
    label: Station
    entity_name: "{{ item.name }}"
    state: PRESENT
  register: station

- name: print Station vertex stats
  ansible.builtin.debug:
    var: station.vertex
