- name: Query path from start_station to end_station
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml
  vars_prompt:
    - name: start_station
      prompt: "Enter start U-Bahn station"
      private: no
    - name: end_station
      prompt: "Enter destination U-Bahn station"
      private: no

  tasks:
    - name: install platform42.neo4j dependencies
      ansible.builtin.include_tasks: tasks/dependencies/neo4j.yml
      
    - name: shortest path
      platform42.neo4j.query_read:
        neo4j_uri: "{{ NEO4J_URI }}"
        database: "{{ NEO4J_DATABASE }}"
        username: "{{ NEO4J_USERNAME }}"
        password: "{{ NEO4J_PASSWORD }}"
        query: |
          MATCH path = shortestPath(
            (start:Station {entity_name: $start_station})-[:TRACK*]->(end:Station {entity_name: $end_station})
          )
          WITH nodes(path) AS ns, relationships(path) AS rs
          RETURN
            REDUCE(output = ns[0].entity_name,
              i IN RANGE(0, size(rs)-1) | output + 
              " — (" + 
              coalesce(rs[i].line, "?") + 
              "|" + 
              coalesce(rs[i].distance, "?") + 
              "km) -> " + 
              ns[i+1].entity_name
            ) AS route;
        parameters:
          start_station: "{{ start_station }}"
          end_station: "{{ end_station }}"
      register: data

    - name: print
      ansible.builtin.debug:
        var: data.query_read.cypher_response[0].route
